
version: '3'

services:
  db:
    image: postgres
    container_name: postgres
    ports:
      - "5430:5432"
  web:
    container_name: django
    build: .
    image: finxi
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
