# Generated by Django 2.0.7 on 2018-07-17 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finxi_web', '0002_create_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='lat',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='lng',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
    ]
